---
title: "Curriculum Vitae"
author: "Andrés González Santa Cruz"
# Quarto PDF settings:
format:
  pdf:
    template: awesome-cv.tex  # Use local template file
    pdf-engine: xelatex       # Awesome CV requires XeLaTeX
    pdf-engine-opt: "-interaction=nonstopmode"
    number-sections: false
    keep-md: true
papersize: A4
linestretch: 1.05
geometry: margin=1in
mainfont: "Latin Modern Roman"
date: "Last updated: `r format(Sys.Date(), '%B %Y')`"
editor: visual
---

```{r setup, include=FALSE}
# Quarto/R Setup
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# Load packages
packages <- c(
  "vitae",    # LaTeX CV templates
  "tibble",   # Data structure for tribbles
  "dplyr",
  "magrittr", # Pipe %>%
  "glue",     # String manipulation
  "here",
  "readr"
)
xfun::pkg_attach2(packages, message = FALSE)

load("cv_data.RData")

```


# Experiencia laboral

```{r EMPLOYMENT}
work %>%
  detailed_entries(
    with  = title,
    what  = unit,
    when  = glue("{startMonth} {startYear} --> {endMonth} {endYear}", .na = ""),
    where = where
    # why = detail  # Uncomment if you want descriptions
  )

```

# Actividades de investigación
## Publicaciones

```{r pubs}
pubs %>%
  detailed_entries(
    #with = area,
    #what = accomplishment,
    why = detail,
    when = as.character(year)
    #where = where
  )
```

<br>

## Seminarios/congresos

```{r sem}
#\pagebreak
sem %>%
  detailed_entries(
    #with = area,
    #what = accomplishment,
    why = detail,
    when = year,
    where = where
  )
```

<br>

# Estudios formales de interés

```{r EDUCATION}
edu %>%
  detailed_entries(
    with = inst,
    what = degree,
    #why = detail,
    when = ifelse(is.na(endYear),glue::glue("{startYear} --> Presente",.na = ""),glue::glue("{startYear} --> {endYear}",.na = "")),
    where = where
  )
```

