---
name: Andrés
surname: González Santa Cruz
position: "Estudiante Doctorado en Salud Pública UCH"
address: "Santiago de Chile"
email: "gonzalez.santacruz.andres@gmail.com"
github: AGSCL
linkedin: andrés-gonzález-santa-cruz
orcid: 0000-0002-5166-9121
date: "`r readr::parse_date(format(Sys.time(), '%d %B %Y'),'%d %B %Y',locale=readr::locale('en'))`"
headcolor: 2f40d8
docname: CV proveniente de \href{hhttps://github.com/AGSCL/CV}{https://github.com/AGSCL/CV}
output: 
  vitae::awesomecv:
    pandoc_args: ["--lua-filter=lua/strong.lua"] 
    keep_tex: false
    latex_engine: xelatex   
header-includes:
- \geometry{left=.5cm, top=.75cm, right=.5cm, bottom=.75cm, footskip=0.5cm}
- \setlength{\parskip}{0.5em}      # Adjusts spacing between paragraphs
- \setlength{\baselineskip}{1.2em} # Adjusts line spacing within paragraphs
---

```{r setup, include=FALSE}
#"pdflatex", "lualatex", "xelatex",:'arg' should be one of "pdflatex", "lualatex", "xelatex", "tectonic"
options(encoding = "UTF-8")
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
require(xfun)
packages <- c('vitae'     # The CV's LaTeX Template
             ,'tibble'    # Data structure for tribbles
             ,'magrittr'  # The Pipe %>%
             ,'here'      # Relative File Paths
             ,'readr'     # Data Loading
             ,'glue'      # String Manipulation
            )
xfun::pkg_attach2(packages, message = FALSE)

options(encoding = "UTF-8")
load("cv_data.RData")

```

# Experiencia laboral
\fontsize{9pt}{1em}\color{text}
```{r EMPLOYMENT}
work %>%
  detailed_entries(
    with = title,
    what = unit,
    #why = detail,
    when = glue::glue("{startMonth} {startYear} --> {endMonth} {endYear}",.na = ""),
    where = where
  )

```

# Actividades de investigación
## Publicaciones
\fontsize{9.5pt}{1.2em}\color{text}
```{r pubs}
pubs %>%
  detailed_entries(
    #with = area,
    #what = accomplishment,
    why = detail,
    when = as.character(year)
    #where = where
  )
```

<br>

\vspace{0.8cm}

## Seminarios/congresos
\fontsize{9.5pt}{1.2em}\color{text}
```{r sem}
#\pagebreak
sem %>%
  detailed_entries(
    #with = area,
    #what = accomplishment,
    why = detail,
    when = year,
    where = where
  )
```

<br>

# Estudios formales de interés
\fontsize{9.5pt}{1.2em}\color{text}
```{r EDUCATION}
edu %>%
  detailed_entries(
    with = inst,
    what = degree,
    #why = detail,
    when = ifelse(is.na(endYear),glue::glue("{startYear} --> Presente",.na = ""),glue::glue("{startYear} --> {endYear}",.na = "")),
    where = where
  )
```

\pagebreak

\linebreak